Update vbn

diff --git a/vbn b/vbn
--- a/vbn
+++ b/vbn
@@ -165,6 +165,21 @@ vmlist='{
         "hostfwd": "tcp::18022-:22, tcp::11306-:11306",
         "default_command": "qemu-system-x86_64 -m 1G -nographic -netdev user,id=n1,hostfwd=tcp::18022-:22,hostfwd=tcp::11306-:11306 -device virtio-net,netdev=n1 -hda ${HOME}/.vbn_vms/bt_alpine-3.18.0-x86_64.qcow2",
         "custom_command": "qemu-system-x86_64 -hda ${HOME}/.vbn_vms/bt_alpine-3.18.0-x86_64.qcow2 "
+    },"kali":{
+        "iso": "kali nethunter-rootless 2024.1",
+        "filename": "",
+        "install": "",
+        "installed_by": "Yi ming",
+        "allocation_size": "",
+        "actual_size": "11G",
+        "format": "",
+        "username": "",
+        "password": "",
+        "download": "wget -O ${HOME}/.vbn_vms/kali-arm64.tgz --no-check-certificate https://onw.cc/1drv.ms.php?url=https://1drv.ms/u/s\\!AkrWd-0Zuuopwyhxlpya4jcVZh6R && tar -zxf ${HOME}/kali-arm64.tgz && rm -f ${HOME}/kali-arm64.tgz && wget -O $PREFIX/bin/nethunter --no-check-certificate https://onw.cc/1drv.ms.php?url=https://1drv.ms/u/s\\!AkrWd-0Zuuopwyn-zSz0k3okLQMA && chmod +x PREFIX/bin/nethunter",
+        "notes": "kali官方的Termux版本\n\n\t文档: https://www.kali.org/docs/nethunter/nethunter-rootless",
+        "hostfwd": "",
+        "default_command": "nethunter",
+        "custom_command": ""
     }
 }'
 
@@ -213,16 +228,30 @@ install_vm() {
     if echo ${vmlist} | jq -e ".${1}" > /dev/null; then
         # Check whether the VM file exists
         # 检查是否存在虚拟机文件
-        vm_file=`echo ${vmlist} | jq -r ".${1}.filename"`
-        if [ -f "${HOME}/.vbn_vms/${vm_file}" ]; then
-            read -p "The VM file is detected. Do you want to continue downloading? (y/n): " input
-            if [ ${input} = "y" ]; then
-                echo -e "\033[33mOverlay download\033[0m"
-            else
-                echo -e "\033[33mInvalid selection, exit\033[0m"
-                exit 0
+        if [ "${1}" = "kali" ]; then
+             if [ -d "${HOME}/kali-arm64" ]; then
+                read -p "The VM file is detected. Do you want to continue downloading? (y/n): " input
+                if [ ${input} = "y" ]; then
+                    echo -e "\033[33mOverlay download\033[0m"
+
+                else
+                    echo -e "\033[33mInvalid selection, exit\033[0m"
+                    exit 0
+                fi
+            fi
+        else
+            vm_file=`echo ${vmlist} | jq -r ".${1}.filename"`
+            if [ -f "${HOME}/.vbn_vms/${vm_file}" ]; then
+                read -p "The VM file is detected. Do you want to continue downloading? (y/n): " input
+                if [ ${input} = "y" ]; then
+                    echo -e "\033[33mOverlay download\033[0m"
+                else
+                    echo -e "\033[33mInvalid selection, exit\033[0m"
+                    exit 0
+                fi
             fi
         fi
+
 
         # Download process
         download=`echo ${vmlist} | jq -r ".${1}.download"`
@@ -272,8 +301,18 @@ install:
     "del")
         # Deleting a VM
         # 删除指定虚拟机
-        if [ -n "$2" ]; then
+        if [ -n "${2}" ]; then
             if echo ${vmlist} | jq -e ".${2}" > /dev/null; then
+                if [ "${2}" = "kali" ]; then
+                    if [ ! -d "${HOME}/kali-arm64" ]; then
+                        echo -e "\033[33mNo VM is installed\033[0m"
+                        exit 1
+                    else
+                        rm -rf "${HOME}/kali-arm64"
+                        rm -f "${PREFIX}/bin/nethunter"
+                        echo -e "\033[32mThe VM is deleted successfully\033[0m"
+                    fi
+                fi
                 # Check whether the VM file exists
                 # 检查是否存在虚拟机文件
                 vm_file=`echo ${vmlist} | jq -r ".${2}.filename"`
@@ -323,8 +362,18 @@ info:
             if echo ${vmlist} | jq -e ".${2}" > /dev/null; then
                 # Check whether the VM file exists
                 # 检查是否存在虚拟机文件
-                vm_file=`echo ${vmlist} | jq -r ".${2}.filename"`
-                vm_file_exits ${vm_file}
+                if [ "${2}" = "kali" ]; then
+                    if [ ! -d "${HOME}/kali-arm64" ]; then
+                        echo -e "\033[33mNo VM is installed\033[0m"
+                        exit 1
+                    else
+                        rm -rf "${HOME}/kali-arm64"
+                        echo -e "\033[32mThe VM is deleted successfully\033[0m"
+                    fi
+                else
+                    vm_file=`echo ${vmlist} | jq -r ".${2}.filename"`
+                    vm_file_exits ${vm_file}
+                fi
                 start_vm=`echo ${vmlist} | jq -r ".${2}.default_command"`
                 if [ -n "$3" -a "$3" = "-D" ]; then
                     eval ${start_vm} &> /dev/null &
@@ -353,6 +402,10 @@ start:
             if echo ${vmlist} | jq -e ".${2}" > /dev/null; then
                 # Check whether the VM file exists
                 # 检查是否存在虚拟机文件
+                if [ "${2}" = "kali" ]; then
+                    echo -e "\033[33mOperation kali is not supported\033[0m"
+                    exit 0
+                fi
                 vm_file=`echo ${vmlist} | jq -r ".${2}.filename"`
                 vm_file_exits ${vm_file}
                 start_vm=`echo ${vmlist} | jq -r ".${2}.custom_command"`
@@ -381,6 +434,10 @@ start:
         # 尽可能在虚拟机内正常关机
         if [ -n "$2" ] ;then
             if echo ${vmlist} | jq -e ".${2}" > /dev/null; then
+                if [ "${2}" = "kali" ]; then
+                    echo -e "\033[33mOperation kali is not supported\033[0m"
+                    exit 0
+                fi
                 vm_file=`echo ${vmlist} | jq -r ".${2}.filename"`
                 vm_file_exits ${vm_file}
                 vm_pid=`ps -u | grep ${vm_file} | grep -v grep | awk '{print $2}'`
@@ -414,6 +471,10 @@ stop:
         # 获取虚拟机运行状态
         if [ -n "$2" ] ;then
             if echo ${vmlist} | jq -e ".${2}" > /dev/null; then
+                if [ "${2}" = "kali" ]; then
+                    echo -e "\033[33mOperation kali is not supported\033[0m"
+                    exit 0
+                fi
                 vm_file=`echo ${vmlist} | jq -r ".${2}.filename"`
                 vm_file_exits ${vm_file}
                 vm_pid=`ps -u | grep ${vm_file} | grep -v grep | awk '{print $2}'`
@@ -446,6 +507,10 @@ status:
                 # 添加快照
                 if [ -n "$3" ] ;then
                     if echo ${vmlist} | jq -e ".${3}" > /dev/null; then
+                        if [ "${3}" = "kali" ]; then
+                            echo -e "\033[33mOperation kali is not supported\033[0m"
+                            exit 0
+                        fi
                         vm_file=`echo ${vmlist} | jq -r ".${3}.filename"`
                         vm_file_exits ${vm_file}
                         if [ -n "$4" ] ;then
